config/routes.rb
Rails.application.routes.draw do
  root 'mainpage#index'

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
             controllers: {
                       omniauth_callbacks: 'users/omniauth_callbacks'
             }
  as :user do
    # session handling
    get     '/login'  => 'users/sessions#new',     as: 'new_user_session'
    post    '/login'  => 'users/sessions#create',  as: 'user_session'
    #delete  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'
    get  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/registration' => 'users/registrations#new',    as: 'new_user_registration'
    post  '/registration' => 'users/registrations#create', as: 'user_registration'

    scope '/account' do
      # password reset
      get   '/reset-password'        => 'users/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'users/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'users/passwords#create'
      get   '/reset-password/change' => 'users/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'users/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'users/confirmations#create'
      get   '/confirm/resend' => 'users/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'users/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'users/registrations#update'

      # account deletion
      delete '' => 'users/registrations#destroy'
    end
  end
  # auth end

  namespace :api do
    resources :search, only: :show

    get '/:action' => 'api' # non RESTful api
    post '/:action' => 'api' # non RESTful api
  end

  namespace :admin do
    root 'admin#index'

    get '(/:locale)/partials(/:model)/:partial_name.:partial_suffix' => 'admin#partials'


    # get '/shows/:action' => 'shows'
    # get '/genres/:action' => 'genres'

    # resources :shows, :genres, :translators, :people do
    #   get '/actions/:action', on: :collection, as: :action
    # end

    namespace :api do
      scope "(:locale)" do
        resources :shows, :pshows, :seasons, :episodes, :genres, :translators, :people, :seos do # RESTful api
          get '/1.0/:action', on: :collection # non RESTful api
          post '/1.0/:action', on: :collection
        end
        get '/:action' => 'api' # non RESTful api
        post '/:action' => 'api' # non RESTful api
      end
    end

    get '/:part' => 'admin#index'
    get '/:part/:id' => 'admin#index'
    get '/:part/:id/seo' => 'admin#index'
  end

  get '/calendar' => 'calendar#show', as: :calendar

  get '/:show_slug' => 'shows#detail', format: false, as: :show
  get '/:show_slug/season-:season_number' => 'shows#season', as: :show_season
  get '/:show_slug/season-:season_number/episode-:episode_number' => 'shows#episode', as: :show_episode
  get '/:show_slug/season-:season_number/episode-:episode_number/translator-:translator_id' => 'shows#episode_translation', as: :show_episode_translation

  get '/genres/:genre_slug' => 'genres#detail', as: :genre

  get '/api/manifest/:id' => 'api/api#manifest'
end

app/views/partials/_donat.html.erb
<div class="widget-qiwi">
  <div class="row">
    <div class="small-12 columns text-center widget-pre">
      <p>Дорогие друзья! Спасибо, что среди вас есть те, кому не наплевать на судьбу нашего ресурса. В прошлом месяце,
        благодаря самым отзывчивым из вас, нам удалось собрать <b><%= Donation.prev_month.round %> р.</b>
        Это в несколько раз меньше того, сколько мы тратим ежемесячно, но эта помощь очень важна.
        Большое спасибо вам за активную поддержку!</p>

      <h5>В этом месяце собрано: <b><%= Donation.current_month.round %> р.</b> (<%= Donation.current_month_progress %>%)</h5>
      <div class="progress small-12 large-8 primary round">
        <span class="meter" style="width: <%= Donation.current_month_progress %>%"></span>
      </div>

      <h2>Поддержите нас!</h2>

      <p>Количество постоянных посетителей нашего сайта растет с каждым днем.
        И это не удивительно, ведь только у нас вы можете посмотреть свои любимые сериалы без надоедливой рекламы и бесконечных попап окон.
        Однако на поддержание работоспособности ресурса приходится платить не малые деньги.
        И платить приходится нам из своего кармана, который увы, не резиновый.
        На данный момент - это <b>18 000 р.</b> ежемесячно.</p>

      <p>Если вы хотите и дальше смотреть ваши любимые сериалы у нас и пользоваться новым функционалом,
        который будет разрабатываться только при вашей поддержке, не поленитесь, поддержите проект.</p>

      <p>P.S.: в сообщении оставляйте пожелания по функционалу.
        В ближайшее время планируем вывести страницу с сообщениями от донатеров в реальном ремени и шкалу
        с собранными в этом месяце средствами. </p>
    </div>
    <div class="small-12 columns text-center widget-body">
      <a href="http://donatepay.ru/donation/hdserialstv" target="_blank" class="button">Поддержать!</a>
    </div>
  </div>
</div>
</div>

app/views/partials/_footer.html.erb
<footer>
  <div class="row">
    <div class="columns small-12">
      <p>Ресурс hd-serials.tv действует в соответствии с законодательством Российской Федерации о защите информации и авторских прав.</p>
      <p>Весь размещенный на сайте контент представляет собой материал, находящийся в свободном доступе для просмотра и скачивания в сети Интернет. </p>
    </div>
  </div>
</footer>

app/views/partials/_modals.html.erb
<script type="text/ng-template" id="messageMdl">
  <div class="padded-content-wrapper">
    <div class="row modal-header">
      <div class="small-12 columns">
        <h1>Внимание</h1>
      </div>
    </div>
    <div class="row modal-body">
      <div class="small-12 columns">
        {{message}}
      </div>
    </div>
  </div>
</script>

app/views/partials/_share.html.erb
<div class="row p-t-20">
  <div class="small-12 columns">
    <div class="share-button">
      <a class="social-share vk"
         data-sharebox="vkontakte"
         data-link="<%= request.url %>"
         title="Поделиться ВКонтакте" rel="nofollow" target="_blank">
        <span class="social-icon">
          <svg pointer-events="none" height="20" width="20">
            <path d="M9.7 15h1.3s.4 0 .6-.2l.2-.5s0-1.6.7-1.8c.7-.2 1.7 1.5 2.6 2.1.7.5 1.3.4 1.3.4h2.6s1.4-.1.7-1.1c-.1-.1-.4-.8-2-2.2-1.7-1.5-1.4-1.3.6-3.9 1.2-1.6 1.7-2.6 1.5-3-.2-.4-1-.3-1-.3h-2.9s-.2 0-.4.1c-.3-.1-.4.2-.4.2s-.4 1.3-1.1 2.4c-1.3 2.2-1.9 2.3-2 2.2-.5-.3-.4-1.3-.4-2 0-2.1.4-3.1-.7-3.3-.3-.1-.6-.1-1.4-.1-1 0-2 0-2.4.3-.3.3-.5.6-.4.6.2 0 .7.1.8.5.3.4.3 1.3.3 1.3s.2 2.5-.4 2.9c-.4.2-.9-.2-2.1-2.2-.6-1-1-2.1-1-2.1s-.1-.3-.3-.5c-.2-.1-.5-.1-.5-.1h-2.8s-.4 0-.6.2c-.1.2 0 .5 0 .5s2.1 5.1 4.7 7.6c2.4 2.2 4.9 2 4.9 2z" fill="#fff"></path>
            <image src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAADFBMVEVPgqxRhKtQg6tRhKsPNB+OAAAABHRSTlMB/mK2wbxAuQAAAExJREFUeNq1jkkOACAMAin8/88S0Zgar87ByrQu+AGN1zJKdF5JKW6aFKfTKyKjS55bZjMyh012qg3zfjUQ1KQuq5cFm2X//A1J/GAA0BEA7WTJ8a8AAAAASUVORK5CYII=" height="20" width="20"></image>
          </svg>
        </span>
        <span class="social-counter" data-ng-bind="like.count">0</span>
      </a>
    </div>
    <div class="share-button">
      <a class="social-share fb"
         data-sharebox="facebook"
         data-link="<%= request.url %>"
         title="Поделиться в Facebook" rel="nofollow" target="_blank">
        <span class="social-icon">
          <svg pointer-events="none" height="20" width="20">
            <path d="M14 1v3s-2.5-.8-3 0c-.3.4 0 2.1 0 3h3c-.2 1-.9 2.1-1.1 3h-1.9v9h-4v-9h-2v-3h2c.1-2 0-4 1-5 1.1-1.1 2.8-1 6-1z" fill="#fff"></path>
            <image src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAARElEQVR4AWMgFShFzDJgoAQoR8zuV46c/Q8dU2QY1QwEaaSpgchyg9NAsmMYpJkQpqqBoNin0EBMrw+nWB41cNRA+gMAp2rGM++9ftQAAAAASUVORK5CYII=" height="20" width="20"></image>
          </svg>
        </span>
        <span class="social-counter" data-ng-bind="like.count">0</span>
      </a>
    </div>
    <div class="share-button">
      <a class="social-share gp"
         data-sharebox="google"
         data-link="<%= request.url %>"
         title="Поделиться в Google+" rel="nofollow" target="_blank">
        <span class="social-icon">
          <svg pointer-events="none" height="20" width="20">
            <path d="M10.3 11.4l-.9-.7c-.4-.2-.8-.6-.8-1.1 0-.6.4-1 .8-1.3 1.1-.9 2.2-1.8 2.2-3.7 0-2-1.2-3-1.8-3.5h1.6l1.6-1.1h-5.1c-1.4 0-3.4.3-4.9 1.6-1.1 1-1.7 2.3-1.7 3.5 0 2 1.6 4.1 4.3 4.1.3 0 .5 0 .8-.1-.1.3-.3.6-.3 1 0 .8.4 1.3.8 1.8-1.2.1-3.4.2-5 1.2-1.5.9-2 2.2-2 3.2.1 1.9 1.9 3.7 5.7 3.7 4.5 0 6.8-2.5 6.8-4.9 0-1.8-1-2.7-2.1-3.7zm-3.5-3c-2.2 0-3.3-2.9-3.3-4.6 0-.7.1-1.4.6-1.9.5-.6 1.2-.9 1.9-.9 2.2 0 3.3 2.9 3.3 4.8 0 .5-.1 1.3-.7 1.9-.4.4-1.1.7-1.8.7zm.1 10.5c-2.8 0-4.6-1.3-4.6-3.2 0-1.9 1.7-2.5 2.2-2.7 1.1-.4 2.5-.4 2.7-.4h.6c2 1.4 2.8 2.1 2.8 3.4.1 1.7-1.2 2.9-3.7 2.9zM20 8h-3v-3h-2v3h-3v2h3v3h2v-3h3z" fill="#fff"></path>
            <image src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAADFBMVEXkXz/lYULlYEHlYUGdtwQIAAAABHRSTlMB/Fayfn+jOQAAAGNJREFUeNpdj1EOgDAMQgfc/85qafJUPpbtrQF6HlmV57UodqScl6SeMiwdMaPA84MCjlehC72QCCuktmXHtSpuNBALSlPh5xkpS6kUb5y/Cw0Fcg2QlQ3Eqr/s41vL6DgfkAvcoAEMV9XyhwAAAABJRU5ErkJggg==" height="20" width="20"></image>
          </svg>
        </span>
        <span class="social-counter" data-ng-bind="like.count">0</span>
      </a>
    </div>
  </div>
</div>

app/views/partials/_top_menu.html.erb
<ul class="title-area">
  <li class="name">
    <h1><a href="/">HD Serials</a></h1>
  </li>
  <li class="toggle-topbar menu-icon"><a href="#"><span>Меню</span></a></li>
</ul>
<section class="top-bar-section">
  <!-- Right Nav Section -->
  <!--<ul class="right">-->
    <!--<li><a href="#" class="link">Вход</a></li>-->
  <!--</ul>-->
  <div data-site-search class="right site-search hide-for-small-only">
    <noindex>
    <form name="search_form" data-ng-submit="search.goSearch()">
    <ul class="menu">
      <li><input type="search" placeholder="Поиск по сериалам" data-ng-model="search.phrase"></li>
      <li><button data-ng-click="search.goSearch()" type="button" class="button">Найти</button></li>
    </ul>
      <div ng-cloak class="search-result" data-ng-if="search.showFounded() || search.nothingFound()">
        <div ng-if="search.nothingFound()" class="nothing-found">По вашему запросу ничего не найдено</div>
        <div class="items">
          <div class="item" data-ng-class="{'last': $last}" data-ng-repeat="item in search.result_existed">
            <div class="poster">
              <a href="/{{item.existed.slug_ru}}"><img data-ng-src="{{item.image}}"></a>
            </div>
            <div class="body">
              <div class="title"><a href="/{{item.existed.slug_ru}}">{{item.existed.title_ru}}</a></div>
              <div class="en-title">{{item.existed.title_en}} ({{item.existed.year}})</div>
              <div class="seasons">
                <div class="season" data-ng-class="{'last': $last}" ng-repeat="season in item.existed_seasons">
                  <a data-ng-href="{{search.getSeasonLink(item, season.slug_ru)}}">Сезон {{season.number}}</a> <span>({{season.aired_episodes}} из {{season.episode_count}})</span>
                </div>
              </div>
            </div>
          </div>
          <div class="other-title" data-ng-if="search.otherShows()">Другие сериалы<span>их пока нет на нашем сайте:</span></div>
          <div class="item" data-ng-class="{'last': $last}" data-ng-repeat="item in search.result_not_existed">
            <div class="poster">
              <img data-ng-src="{{item.image}}">
            </div>
            <div class="body">
              <div class="title">{{item.ruTitle}}</div>
              <div class="en-title">{{item.title}}</div>
            </div>
          </div>
        </div>
      </div>
    </form>
    </noindex>
  </div>
  <!-- Left Nav Section -->
  <ul class="left">
    <li class="has-dropdown">
      <a href="#">Жанры</a>
      <ul class="dropdown">
        <% genres_list.each do |genre| %><li><a href="<%= genre_path genre.slug_ru %>" class="<%= cp(genre_path genre.slug_ru) %>"><%= genre.name_ru %></a></li><%end %>
      </ul>
    </li>
    <li class="divider"></li>
    <!--<li><a href="#">Последние обновления</a></li>-->
    <li><a href="<%= calendar_path %>">Календарь выхода серий</a></li>
  </ul>
</section>