config/routes.rb
Rails.application.routes.draw do
  root 'mainpage#index'

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
             controllers: {
                       omniauth_callbacks: 'users/omniauth_callbacks'
             }
  as :user do
    # session handling
    get     '/login'  => 'users/sessions#new',     as: 'new_user_session'
    post    '/login'  => 'users/sessions#create',  as: 'user_session'
    #delete  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'
    get  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/registration' => 'users/registrations#new',    as: 'new_user_registration'
    post  '/registration' => 'users/registrations#create', as: 'user_registration'

    scope '/account' do
      # password reset
      get   '/reset-password'        => 'users/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'users/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'users/passwords#create'
      get   '/reset-password/change' => 'users/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'users/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'users/confirmations#create'
      get   '/confirm/resend' => 'users/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'users/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'users/registrations#update'

      # account deletion
      delete '' => 'users/registrations#destroy'
    end
  end
  # auth end

  namespace :api do
    resources :search, only: :show

    get '/:action' => 'api' # non RESTful api
    post '/:action' => 'api' # non RESTful api
  end

  namespace :admin do
    root 'admin#index'

    get '(/:locale)/partials(/:model)/:partial_name.:partial_suffix' => 'admin#partials'


    # get '/shows/:action' => 'shows'
    # get '/genres/:action' => 'genres'

    # resources :shows, :genres, :translators, :people do
    #   get '/actions/:action', on: :collection, as: :action
    # end

    namespace :api do
      scope "(:locale)" do
        resources :shows, :pshows, :seasons, :episodes, :genres, :translators, :people, :seos do # RESTful api
          get '/1.0/:action', on: :collection # non RESTful api
          post '/1.0/:action', on: :collection
        end
        get '/:action' => 'api' # non RESTful api
        post '/:action' => 'api' # non RESTful api
      end
    end

    get '/:part' => 'admin#index'
    get '/:part/:id' => 'admin#index'
    get '/:part/:id/seo' => 'admin#index'
  end

  get '/calendar' => 'calendar#show', as: :calendar

  get '/:show_slug' => 'shows#detail', format: false, as: :show
  get '/:show_slug/season-:season_number' => 'shows#season', as: :show_season
  get '/:show_slug/season-:season_number/episode-:episode_number' => 'shows#episode', as: :show_episode
  get '/:show_slug/season-:season_number/episode-:episode_number/translator-:translator_id' => 'shows#episode_translation', as: :show_episode_translation

  get '/genres/:genre_slug' => 'genres#detail', as: :genre

  get '/api/manifest/:id' => 'api/api#manifest'
end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
  def index
    @new_shows = Show.order(:first_aired => :desc).take(6)

    @new_episodes = Episode.includes(:translations)
                        .order(:first_aired => :desc)
                        .where("first_aired <= ?", Date.today).where.not(translations: {id: nil})
                        .limit(12)

    if Rails.env.development?
      best_kp_ratings   = Rating.joins(:kp_rating).order("kp_ratings.value DESC").where("value > 7.5").select(:id).limit 15
      best_imdb_ratings = Rating.joins(:imdb_rating).order("imdb_ratings.value DESC").where("value > 7.5").select(:id).limit 15
      top = Show.joins(:rating)
              .where("ratings.id in (?) and ratings.id in (?)", best_kp_ratings, best_imdb_ratings)
              .sort_by do |s|
                - s.rating.imdb_rating.value * s.rating.kp_rating.value / 2
              end
    else
      top = Show.where(id: [20, 29, 33, 17, 18, 22, 31, 32, 39, 81])
    end

    @top_ten = top[0...10]

    rand_shows = Show.where("first_aired > ?", Date.today - 2.year)
    random_seed = rand(rand_shows.size)
    @random_show = rand_shows.offset(random_seed).first

    @popular_shows = Show.where(title_ru: [
        "Игра престолов",
        "Сверхъестественное",
        "Ходячие мертвецы",
        "Стрела",
        "Гримм",
        "Физрук",
        "Дневники вампира",
        "Викинги",
        "Интерны",
        "Теория большого взрыва",
        "Флэш",
        "Сотня",
        "Форс-мажоры"
    ]).take(12)
  end
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/views/mainpage/index.html.erb
<%
   title "HD-Serials - Смотреть сериалы онлайн в высоком качестве (HD, 720p) бесплатно без рекламы"
   description "Смотреть сериалы онлайн в высоком качестве (HD, 720p) бесплатно без рекламы"
   keywords "Сериалы, смотреть онлайн, без рекламы, бесплатно, без регистрации, HD, качество, высокое качество, с телефона, с планшета"
%>
<section class="main-page-fanart page-fanart show-for-medium-up" data-no-transition-cache>
  <article class="fanart-slide">
    <h1 class="title_ru"><a href="<%= show_path @random_show.slug_ru %>"><%= @random_show.title_ru %></a></h1>
    <div class="title_en"><%= @random_show.title_en %></div>
    <% if @random_show.rating.present? %>
    <div class="awwards-list">
      <div class="awwards imdb"><div class="count"><%= @random_show.rating.imdb_rating.value %></div></div>
      <div class="awwards kinopoisk"><div class="count"><%= number_with_precision @random_show.rating.kp_rating.value, precision: 1 %></div></div>
    </div>
    <% end %>
  </article>
  <img src="<%= @random_show.fanart.url(:original) %>" alt="<%= @random_show.title_ru %>"/>
</section>

<section class="main-page">
    <div class="row">
      <div class="medium-8 column popular">
        <h4>Популярные сериалы</h4>
        <ul class="small-block-grid-3 medium-block-grid-4 large-block-grid-6">
          <% @popular_shows.each do |s| %>
          <li class="show_item">
            <a href="<%= show_path(s.slug_ru) %>"><%= image_tag s.poster.url(:thumb), alt: s.title_ru%></a>
            <%= link_to s.title_ru, show_path(s.slug_ru), class:"title"  %>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="medium-4 column new">
        <h4>Новые сериалы</h4>
        <ul class="small-block-grid-3 medium-block-grid-2 large-block-grid-3">
          <% @new_shows.each do |s| %>
              <li class="show_item">
                <a href="<%= show_path(s.slug_ru) %>"><%= image_tag s.poster.url(:thumb), alt: s.title_ru%></a>
                <%= link_to s.title_ru, show_path(s.slug_ru), class:"title"  %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= render "partials/donat" %>
    <%= render "partials/banner" %>
    <div class="row">
      <div class="small-12 medium-8 medium-push-4 column new-episodes">
          <h4>Новые эпизоды</h4>
          <ul class="small-block-grid-3 medium-block-grid-3 large-block-grid-4">
            <% @new_episodes.each do |s| %>
                <li class="show-episode">
                  <div class="show-screenshot">
                      <a href="<%= show_episode_path(s.show.slug_ru, "%02d" % s.season.number, "%02d" % s.number) %>">
                        <img src="<%= s.screenshot.url(:thumb) %>"/>
                      </a>
                  </div>
                  <div class="show-title">
                    <a href="<%= show_episode_path(s.show.slug_ru, "%02d" % s.season.number, "%02d" % s.number) %>"><%= s.show.title_ru %></a>
                  </div>
                  <div class="show-meta">сезон <%= s.season.number %>, эпизод <%= s.number %></div>
                  <div class="episode-date"><%= Russian::strftime(s.first_aired, "%e %B %Y")%></div>
                </li>
            <% end %>
          </ul>
      </div>
      <div class="small-12 medium-4 medium-pull-8 column">
        <div class="about-block">
            <h5>Бесплатный онлайн кинотеатр<br>HD-Serials.TV: фильмы в хорошем качестве всегда приносят настоящее удовольствие</h5>
            <p>Каждый день миллионы людей ищут фильмы онлайн и никто не хочет усложнять себе жизнь – и вы наверняка один из них!
              А раз так, то HD-Serials.TV – это именно тот ресурс, который вам нужен, если вы хотите смотреть фильмы онлайн бесплатно и
              без регистрации. Потому что именно наш сайт является настоящим Эльдорадо для киноманов.</p>
            <p>Мы дарим вам смех, адреналин, взрывные эмоции – а вы при этом не тратите ничего! Хотите смотреть кино
              без регистрации? Пожалуйста, выбирайте и смотрите – мы экономим ваше время. На сайте доступен бесплатный
              просмотр фильмов – мы экономим ваши деньги. И нет, все вышесказанное не значит, что картины будут в плохом качестве.
              Как раз наоборот! И мы снова экономим – ваши усилия, которые могли быть потрачены на попытки разобрать невнятные диалоги,
              некачественный перевод, расплывчатую картинку.</p>
            <p>Быстро, бесплатно, захватывающе – вот что такое кинопросмотр с HD-Serials.TV!</p>
        </div>
      </div>
    </div>
    <section class="top-ten row hide-for-small p-t-30">
        <div class="small-12">
          <h2>ТОП-10 сериалов</h2>
          <ul class="medium-block-grid-4 large-block-grid-5 p-t-20">
            <% @top_ten.each do |s| %>
              <li>
                <article class="top-ten-item">
                  <div class="poster" data-height-equalize="<%= number_with_precision s.poster.aspect_ratio(:thumb), precision: 3 %>">
                    <a href="<%= show_path s.slug_ru %>"></a>
                    <img src="<%= s.poster.url(:thumb) %>" alt="<%= s.title_ru %>" />
                    <div class="poster pos-<%= s.id %>"></div>
                    <div class="titles">
                      <h1 class="title_ru"><%= s.title_ru %></h1>
                      <div class="title_en"><%= s.title_en %></div>
                      <div class="awwards-list">
                        <div class="awwards imdb"><div class="count"><%= number_with_precision s.rating.imdb_rating.value, precision: 1 %></div></div>
                        <div class="awwards kinopoisk"><div class="count"><%= number_with_precision s.rating.kp_rating.value, precision: 1 %></div></div>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
            <% end %>
          </ul>
        </div>
    </section>
</section>
<div data-google-analytics-tracker
     data-page="<%= request.original_fullpath %>"
     data-title="Главная страница"
></div>

app/views/mainpage/robots.html.erb
User-agent: *
Sitemap: <%= sitemap_url %>