config/routes.rb
Rails.application.routes.draw do
  root 'mainpage#index'

  # Authentication
  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations],
             controllers: {
                       omniauth_callbacks: 'users/omniauth_callbacks'
             }
  as :user do
    # session handling
    get     '/login'  => 'users/sessions#new',     as: 'new_user_session'
    post    '/login'  => 'users/sessions#create',  as: 'user_session'
    #delete  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'
    get  '/logout' => 'users/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/registration' => 'users/registrations#new',    as: 'new_user_registration'
    post  '/registration' => 'users/registrations#create', as: 'user_registration'

    scope '/account' do
      # password reset
      get   '/reset-password'        => 'users/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'users/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'users/passwords#create'
      get   '/reset-password/change' => 'users/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'users/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'users/confirmations#create'
      get   '/confirm/resend' => 'users/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'users/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'users/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'users/registrations#update'

      # account deletion
      delete '' => 'users/registrations#destroy'
    end
  end
  # auth end

  namespace :api do
    resources :search, only: :show

    get '/:action' => 'api' # non RESTful api
    post '/:action' => 'api' # non RESTful api
  end

  namespace :admin do
    root 'admin#index'

    get '(/:locale)/partials(/:model)/:partial_name.:partial_suffix' => 'admin#partials'


    # get '/shows/:action' => 'shows'
    # get '/genres/:action' => 'genres'

    # resources :shows, :genres, :translators, :people do
    #   get '/actions/:action', on: :collection, as: :action
    # end

    namespace :api do
      scope "(:locale)" do
        resources :shows, :pshows, :seasons, :episodes, :genres, :translators, :people, :seos do # RESTful api
          get '/1.0/:action', on: :collection # non RESTful api
          post '/1.0/:action', on: :collection
        end
        get '/:action' => 'api' # non RESTful api
        post '/:action' => 'api' # non RESTful api
      end
    end

    get '/:part' => 'admin#index'
    get '/:part/:id' => 'admin#index'
    get '/:part/:id/seo' => 'admin#index'
  end

  get '/calendar' => 'calendar#show', as: :calendar

  get '/:show_slug' => 'shows#detail', format: false, as: :show
  get '/:show_slug/season-:season_number' => 'shows#season', as: :show_season
  get '/:show_slug/season-:season_number/episode-:episode_number' => 'shows#episode', as: :show_episode
  get '/:show_slug/season-:season_number/episode-:episode_number/translator-:translator_id' => 'shows#episode_translation', as: :show_episode_translation

  get '/genres/:genre_slug' => 'genres#detail', as: :genre

  get '/api/manifest/:id' => 'api/api#manifest'
end

app/controllers/admin/api/shows_controller.rb
class Admin::Api::ShowsController < Admin::Api::ApiController
  def index
    @items = Show.order('id asc').all
  end

  def new
    render json: {}
  end

  def create

  end

  def show
    @item = Show.unscoped.find(params[:id])
  rescue
    not_found
  end

  def edit

  end

  def update
    show = Show.unscoped.find(model_params[:id])

    if model_params[:ids].present? && model_params[:ids].size > 0
      show.update(ids: model_params[:ids])
    end

    show.update(model_params)
    @item = show
    render action: :show
  end

  def destroy
    show = Show.unscoped.find(params[:id])
    show.destroy
    render json: { deleted: true }
  end

  ### non restful

  def deactivate
    show = Show.unscoped.find(params[:id])
    show.updated = nil
    show.save
    sleep 0.5
    @item = show
    render action: :show
  end

  def sync_seasons
    show = Show.unscoped.find params[:id]
    job = Delayed::Job.enqueue SyncAllSeasonsJob.new(show)
    render json: {
               model: show,
               job: job
           }
  end

  def sync_videos
    show = Show.unscoped.find(params[:id])

    if show.ids['kp'].to_i == 0
      return render json: show
    end

    kp = show.ids['kp']

    moonwalk = @moonwalk.show kp

    moonwalk.each do |m|
      translator_id = m['translator_id']
      moonwalk_episodes = @moonwalk.get_playlist_url_parallel kp, translator_id
      moonwalk_episodes[:playlists].each_pair do |season_number, episodes|
        episodes.each_pair do |episode_number, playlists|
          episode = Episode.where(show: show, abs_name: "#{season_number.to_i}-#{episode_number.to_i}").take
          translator = Translator.where(ex_id: translator_id).take
          translation = Translation.where(episode: episode, translator: translator).first_or_create
          translation.moonwalk_token = playlists['token'] unless translation.moonwalk_token == 'temp_token'
          translation.save
        end
      end
    end

    @item = show
    render action: :show, formats: :json
  end

  def sync_ru_names
    show = Show.unscoped.find(params[:id])

    if show.ids['kp'].to_i == 0
      return render json: show
    end

    kp = show.ids['kp']
    kp_episode_names = @kinopoisk.episode_names kp
    show.episodes.each do |episode|
      title_en = episode.title_en
      next if title_en.nil?
      next if title_en.size < 2
      kp_episode_names.each do |key, value|
        next unless value.size > 0
        regexp = Regexp.new("#{title_en}", Regexp::IGNORECASE)
        if key.length > 1
          regexp2 = Regexp.new("#{key}", Regexp::IGNORECASE)
        else
          regexp2 = key
        end
        if key[regexp] || title_en[regexp2]
          episode.title_ru = value
          episode.title_en = key
        end
      end
      episode.save
    end

    @item = show
    render action: :show, formats: :json
  end

  ### end

  private

  def model_params
    params
        .permit(
            :country,
            :slug_ru,
            :slug_en,
            :description,
            :description_ru,
            :description_en,
            :slogan_ru,
            :slogan_en,
            :ended,
            :id,
            :ids,
            :imdbId,
            :kinopoiskId,
            :rating,
            :ruTitle,
            :title,
            :runtime,
            :started,
            :status,
            :tvrageId,
            :year
        )
  end
end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < Admin::AdminController

    def index
        @shows = Show.order('id asc').all
    end

    def new

    end

    def show
      @show = Show.find params['id']
      @seasons = @show.seasons.order :number
    end

    def pending
      @shows = Show.unscoped.where(updated: nil)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :parse_params

  def detail
    @show = Show.find_by_slug_ru @show_slug
    @genres = @show.genres
  end

  def season
    @show = Show.find_by_slug_ru @show_slug
    @season = @show.seasons.where(number: @season_number).take
  end

  def episode
    @show = Show.find_by_slug_ru @show_slug
    @season = @show.seasons.where(number: @season_number).take
    @episode = @season.episodes.where(number: @episode_number).take

    # render_404 if @episode.translations.count < 1
  end

  private

  def parse_params
    @show_slug = params[:show_slug]
    @season_number = params[:season_number].to_i
    @episode_number = params[:episode_number].to_i
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
  def genres_inline_list genres
    g = genres.map do |genre|
      return '' if genre.name_ru.nil?
      "<a href=\"/genres/#{genre.slug_ru}\">#{genre.name_ru}</a>"
    end
    g * ", "
  end

  def genres_array genres
    genres.map do |genre|
      return genre.name_ru unless genre.name_ru.nil?
    end
  end

end

app/views/shows/detail.html.erb
<%
   set_meta_tags title: "#{@show.title_ru} (#{@show.title_en}) - смотреть онлайн в хорошем качестве бесплатно и без рекламы в HD качестве",
                 description: strip_tags(@show.description_ru),
                 keywords: "#{@show.title_ru}, смотреть онлайн, без рекламы, бесплатно, без регистрации, HD, качество, высокое качество, с телефона, с планшета",
                 og: {
                     site_name: 'HD-Serials',
                     title: @show.title_ru,
                     description: strip_tags(@show.description_ru),
                     image: URI.join(request.url, @show.poster.url(:medium)),
                     type: 'video.tv_show',
                     url: URI.join(request.url, show_path(@show.slug_ru))
                 },
                 video: {
                     duration: @show.runtime.minutes,
                     release_date: @show.first_aired.to_time.iso8601
                 }
%>
<div class="show-fanart show-for-medium-up">
  <img src="<%= @show.fanart.url(:original) %>"/>
  <div class="show-info-params">
    <div class="transparent-bg"></div>
    <div class="shadow-bg"></div>
    <div class="row">
      <div class="small-9 small-offset-3 columns">
        <div class="row">
          <div class="small-12 columns show-title">
            <div class="title">
              <h1><%= @show.title_ru %></h1>
              <div class="subtitle"><%= @show.title_en %> (<%= @show.first_aired.year %>, <%= @show.country.upcase %>)</div>
            </div>
            <% unless @show.rating.nil? %>
            <div class="awwards-list">
              <div class="awwards imdb"><div class="count"><%= @show.rating.imdb_rating.value %></div></div>
              <div class="awwards kinopoisk"><div class="count"><%= number_with_precision @show.rating.kp_rating.value, precision: 1 %></div></div>
            </div>
            <% end %>
          </div>
        </div>
        <div class="row additional-info">
          <div class="small-12 columns">
            <span>Канал:</span> <%= @show.network %>,<!-- <%= @show.certification %>,-->
            <%= @show.status %>
            <span>Сезонов:</span> <%= @show.seasons.present.count %>
            <span>Эпизодов:</span> <%= @show.aired_episodes %>
            <span>Продолж.:</span> <%= distance_of_time_in_words @show.runtime.minutes %> (<%= distance_of_time_in_words (@show.runtime * @show.aired_episodes).minutes %>)
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <div class="row show-details p-b-30">
      <div class="medium-3 small-centered medium-uncentered columns show-poster">
        <img src="<%= @show.poster.url(:medium) %>" alt="<%= @show.title_ru  %>"/>
      </div>
      <div class="medium-9 columns show-description">
        <div class="genres-list">Жанры: <%== genres_inline_list @genres %></div>
        <%= render "partials/share" %>
        <div class="description"><%== @show.description_ru %></div>
        <!--<h5>Актеры:</h5>-->
        <!--<div class="people-list">-->
        <!--<ul class="small-block-grid-3 medium-block-grid-5 large-block-grid-6">-->
        <!--<% @show.casts.each do |cast| %>-->
            <!--<li class="item">-->
            <!--<img src="<%= cast.person.headshot.url(:cropped_thumb) %>"/>-->
            <!--<p><%= cast.character %></p>-->
            <!--</li>-->
            <!--<% end %>-->
        <!--</ul>-->
        <!--</div>-->
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
          <ul class="small-block-grid-3 medium-block-grid-5 large-block-grid-6 seasons-list">
            <% @show.seasons.present.each do |s| %>
                <li>
                  <a href="<%= show_season_path @show.slug_ru, "%02d" % s.number %>">
                    <img src="<%= s.poster.url(:thumb) %>"/>
                    <h5 class="season-number">Сезон <%= s.number %></h5>
                  </a>
                </li>
            <%end%>
          </ul>
      </div>
    </div>
  </div>
</div>
<%= render "partials/donat" %>
<div data-google-analytics-tracker
     data-page="<%= request.original_fullpath %>"
     data-title="<%= "Страница сериала: #{@show.title_ru}" %>"
></div>

app/views/shows/episode.html.erb
<%
   if @episode.title_ru.nil? || @episode.title_ru.blank?
     title = "#{@episode.show.title_ru}, #{@episode.season.number} сезон - #{@episode.number} эпизод смотреть онлайн и без рекламы в HD качестве"
   else
     title = "#{@episode.show.title_ru}, #{@episode.season.number} сезон - #{@episode.number} эпизод (#{@episode.title_ru}) смотреть онлайн"
   end

  description = if @episode.description_ru.nil? then '' else @episode.description_ru end

   set_meta_tags(
                 title: title,
                 description: description,
                 keywords: "#{@episode.show.title_ru}, #{@episode.season.number} сезон, #{@episode.number} эпизод, смотреть онлайн, без рекламы, бесплатно, без регистрации, HD, качество, высокое качество, с телефона, с планшета",
                 og: {
                     site_name: 'HD-Serials',
                     title: title,
                     image: URI.join(request.url, @episode.screenshot.url),
                     type: 'video.tv_show',
                     url: URI.join(
                         request.url,
                         show_episode_path(@episode.show.slug_ru, "%02d" % @episode.season.number, "%02d" % @episode.number)
                     )
                 },
                 video: {
                     duration: @show.runtime.minutes,
                     release_date: @show.first_aired.to_time.iso8601,
                     series: URI.join(request.url, show_path(@episode.show.slug_ru))
                 }
            )
%>
<section class="episode">
  <div class="show-fanart">
    <% if @episode.screenshot.exists? %>
      <% if @episode.screenshot.width < 1200 || !@episode.screenshot.exists? %>
        <img src="<%= @show.fanart.url(:original) %>"/>
      <% else %>
        <img src="<%= @episode.screenshot.url(:original) %>"/>
      <% end  %>
    <% else %>
      <img src="<%= @show.fanart.url(:original) %>"/>
    <% end  %>
  </div>
  <div class="row">
    <div class="small-12 column text-center" data-no-transition-cache>
      <h1><%= @episode.title_ru %> <span><%= @episode.title_en %></span></h1>
      <h5><%= @show.title_ru %> (<%= @season_number %> сезон, <%= @episode_number %> эпизод)</h5>
      <%= render "partials/share" %>
      <% unless @episode.description_ru.nil? -%>
        <div class="p-t-20"><%= @episode.description_ru %></div>
      <% end -%>
    </div>
  </div>

  <% if @episode.translations.count > 1  -%>
  <div class="row p-t-30" data-show-translations="<%= @episode.translators_list * "," %>">
    <div class="small-12 columns">
      <% @episode.translations.each do |e| %>
        <div class="translation box row" data-ng-if="translation.is_active(<%= e.translator ? e.translator.id : 0 %>)">
          <% unless @episode.prev.nil? -%>
          <a class="other-episode prev" href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % @episode.prev.number %>">
            <img src="<%= @episode.prev.screenshot.url(:original) %>"/>
            <span>
              Сезон <%= @season.number %> - эпизод <%= @episode.prev.number %> <br/>
              <b><%= @episode.prev.title_ru %></b> <%= @episode.prev.title_en %>
            </span>
          </a>
          <% end -%>
          <div class="small-10 columns push-1">
            <div class="flex-video widescreen">
              <div data-videoplayer="<%= e.id %>"
                   id="player_<%= e.id %>"
                   data-title="<%= "#{@episode.show.title_ru}: #{@episode.season.number} сезон - #{@episode.number} эпизод" %>"
                   <%- if(!e.subtitles.nil? && e.subtitles.size > 0) %>
                   data-subtitles="<%= e.subtitles %>"
                   <% end -%>
                   ></div>
            </div>
          </div>
          <% unless @episode.next.nil? -%>
          <a class="other-episode next" href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % @episode.next.number %>">
            <img src="<%= @episode.next.screenshot.url(:original) %>"/>
            <span>
              Сезон <%= @season.number %> - эпизод <%= @episode.next.number %> <br/>
              <b><%= @episode.next.title_ru %></b> <%= @episode.next.title_en %>
            </span>
          </a>
          <% end -%>
        </div>
      <% end %>
      <div class="translation-buttons text-center">
        <% @episode.translations.each do |e| %>
          <div class="translation button"
               data-ng-click="translation.set(<%= e.translator ? e.translator.id : 0 %>)"
               data-ng-class="translation.bclass(<%= e.translator ? e.translator.id : 0 %>)"><%= e.translator.nil? ? "Оригинал" : e.translator.name%></div>
        <% end %>
      </div>
    </div>
  </div>
  <% else -%>
  <div class="row p-t-30">
    <div class="small-12 columns">
      <div class="translation box row">
      <% @episode.translations.each do |e| %>
        <% unless @episode.prev.nil? -%>
          <a class="other-episode prev" href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % @episode.prev.number %>">
            <img src="<%= @episode.prev.screenshot.url(:original) %>"/>
            <span>
              Сезон <%= @season.number %> - эпизод <%= @episode.prev.number %> <br/>
              <b><%= @episode.prev.title_ru %></b> <%= @episode.prev.title_en %>
            </span>
          </a>
        <% end -%>
        <div class="small-10 columns push-1">
          <div class="flex-video widescreen">
            <div data-videoplayer="<%= e.id %>"
                 id="player_<%= e.id %>"
                 data-title="<%= "#{@episode.show.title_ru}: #{@episode.season.number} сезон - #{@episode.number} эпизод" %>"
                 ></div>
          </div>
        </div>
        <% unless @episode.next.nil? -%>
          <a class="other-episode next" href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % @episode.next.number %>">
            <img src="<%= @episode.next.screenshot.url(:original) %>"/>
            <span>
              Сезон <%= @season.number %> - эпизод <%= @episode.next.number %> <br/>
              <b><%= @episode.next.title_ru %></b> <%= @episode.next.title_en %>
            </span>
          </a>
        <% end -%>
      <% end %>
      </div>
    </div>
  </div>
  <% end -%>
</section>

<%= render "partials/donat" %>

<section class="season p-t-30">
  <div class="row show-details">
    <div class="small-12 columns">
      <h3>Все эпизоды <%= @season.number %> сезона</h3>
      <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4 p-t-20">
        <% @season.episodes.includes(:translations).order(:number).where.not(translations: {id: nil}, screenshot_updated_at: nil).each_with_index do |e, index| %>
          <li class="show-episodes <%= "current" if e.number == @episode_number %>">
            <a href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % e.number %>"><img src="<%= e.screenshot.url(:thumb) %>"/></a>
            <h6>Эпизод <%= e.number %></h6>
            <h5>
              <%= e.title_ru %><br>
              <span><%= e.title_en %></span>
              <span><%= Russian::strftime(e.first_aired, "%d %B %Y") unless e.first_aired.nil? %></span>
            </h5>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row p-t-20">
    <div class="small-12 columns">
      <h3>Другие сезоны</h3>
      <ul class="small-block-grid-3 medium-block-grid-5 large-block-grid-6 seasons-list p-t-20">
        <% @show.seasons.present.where.not( number: @season.number).each do |s| %>
          <li>
            <a href="<%= show_season_path @show.slug_ru, "%02d" % s.number %>">
              <img src="<%= s.poster.url(:thumb) %>"/>
              <h5 class="season-number">Сезон <%= s.number %></h5>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</section>
<div data-google-analytics-tracker
     data-page="<%= request.original_fullpath %>"
     data-title="<%= "Страница эпизода: #{@episode.show.title_ru}: #{@episode.season.number} сезон - #{@episode.number} эпизод" %>"
></div>

app/views/shows/season.html.erb
<%
   description = if @show.description_ru.nil? then '' else strip_tags(@show.description_ru) end
   set_meta_tags title: "#{@show.title_ru} - смотреть #{@season.number} сезон онлайн и без рекламы в HD качестве",
                 description: description,
                 keywords: "#{@show.title_ru}, #{@season.number} сезон, смотреть онлайн, без рекламы, бесплатно, без регистрации, HD, качество, высокое качество, с телефона, с планшета"
%>
<section class="season">
  <div class="show-fanart">
    <img src="<%= @show.fanart.url(:original) %>"/>
  </div>
  <div class="row show-details">
    <div class="small-12 columns">
      <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
        <li class="season-poster">
          <img src="<%= @season.poster.url(:medium) %>" alt="<%= @show.title_ru  %>, сезон <%=@season.number%>"/>
          <h1>
            <%= @show.title_ru %>
            <span>Cезон <%=@season.number%></span>
          </h1>
        </li>
        <% @season.episodes.includes(:translations).order(:number).where.not(translations: {id: nil}, screenshot_updated_at: nil).each_with_index do |e, index| %>
          <li class="show-episodes">
            <a href="<%= show_episode_path @show.slug_ru, "%02d" % @season.number, "%02d" % e.number %>"><img src="<%= e.screenshot.url(:thumb) %>"/></a>
            <h6>Эпизод <%= e.number %></h6>
            <h5>
              <%= e.title_ru %><br>
              <span><%= e.title_en %></span>
              <span><%= Russian::strftime(e.first_aired, "%d %B %Y") unless e.first_aired.nil? %></span>
            </h5>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= render "partials/donat" %>
  <div class="row p-t-20">
    <div class="small-12 columns">
      <h3>Другие сезоны</h3>
      <ul class="small-block-grid-3 medium-block-grid-5 large-block-grid-6 seasons-list p-t-20">
        <% @show.seasons.present.where.not( number: @season.number).each do |s| %>
          <li>
            <a href="<%= show_season_path @show.slug_ru, "%02d" % s.number %>">
              <img src="<%= s.poster.url(:thumb) %>"/>
              <h5 class="season-number">Сезон <%= s.number %></h5>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</section>
<div data-google-analytics-tracker
     data-page="<%= request.original_fullpath %>"
     data-title="<%= "Страница сезона: #{@show.title_ru} - #{@season.number} сезон" %>"
></div>